import type { NextPage } from 'next'
import Head from 'next/head'
import { QueryClient, dehydrate} from "react-query"

import styles from '../styles/Home.module.css'

import { GetLaunchesPastQuery, useGetLaunchesPastQuery } from '../graphql/generated';

const Home: NextPage = (props) => {
  console.log('WHAT PROPS DO WE HAVE?: ', props);
  const { data, isFetching } = useGetLaunchesPastQuery<GetLaunchesPastQuery>({ limit: 5 });

  console.log('DO WE HAVE ANY DATA: ', data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data?.launchesPast && (
          <ul>
            {data?.launchesPast.map((launch) => (
              <li key={launch?.mission_name}>{launch?.mission_name} ({launch?.launch_date_local})</li>
            ))}
          </ul>
        )}
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery(useGetLaunchesPastQuery.getKey(), () =>
    useGetLaunchesPastQuery.fetcher({ limit: 10 })
  );

  return {
    props: {
      dehydratedState: JSON.parse(JSON.stringify(dehydrate(queryClient))),
    },
  };
};

export default Home
